title: Arif Yuliannur programming blog
description: > # this means to ignore newlines until "baseurl:"
  Constant learning, and share while at it.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Arif Yuliannur # add your name
author-img: profpic.jpeg # add your photo
about-author: VP Engineering at Tokenomy | We are Hiring. <br> Code in elixir, python, elm and javascript. This is a learning log. # add description
social-twitter: virkill
social-facebook: virkology # add your Facebook handle
social-github: virkillz # add your Github handle
social-linkedin: arif-yuliannur # add your Linkedin handle
social-email: virkill@gmail.com

# Disqus
discus-identifier: arifvirkillyulian # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
